Workshops SoSe22
fsi-tue/eei pull request #49
Opened 2022-03-09 20:44 UTC by not-a-feature

- Rename anfi to ersti
- Add Workshops for SoSe22
- Improve css / mobile css

2022-03-09 21:58 UTC, Pfonks requested changes
Filmabend should not be activated as of the current plan.

2022-03-10 20:40 UTC, not-a-feature commented
Fixed in [ec2c6ee](https://github.com/fsi-tue/eei/pull/49/commits/ec2c6ee57ac3617404d0e9a7b7123f2fc13f95b4)

2022-03-10 21:09 UTC, Pfonks approved these changes

2022-03-10 22:05 UTC, PhictionalOne approved these changes

2022-03-12 08:41 UTC, merged